parameters:
#    wedding_project.example.class: Wedding\Bundle\ProjectBundle\Example

services:
#    wedding_project.example:
#        class: %wedding_project.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
